/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "segment_constants.h"

namespace Article {

const segmentConstants g_segment_constants;

segmentConstants::segmentConstants() {
}

} // namespace

