/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef segment_CONSTANTS_H
#define segment_CONSTANTS_H

#include "segment_types.h"

namespace Article {

class segmentConstants {
 public:
  segmentConstants();

};

extern const segmentConstants g_segment_constants;

} // namespace

#endif
